#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := run6752_65u_a_l1

MODULES += app/mt_boot \
           dev/lcm

MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += SWCHR_POWER_PATH
DEFINES += MTK_BQ24261_SUPPORT
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM="hx8394d_hd720_dsi_vdo"

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes

BOOT_LOGO := cu_lte_hd720
DEBUG := 0
#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y

CUSTOM_LK_USB_UNIQUE_SERIAL=no
